CREATE table si(
id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
si VARCHAR(50) NOT NULL
);

INSERT INTO si VALUES(NULL, "서울특별시");
INSERT INTO si VALUES(NULL, "부산광역시");
INSERT INTO si VALUES(NULL, "대구광역시");
INSERT INTO si VALUES(NULL, "대전광역시");
INSERT INTO si VALUES(NULL, "인천광역시");
INSERT INTO si VALUES(NULL, "광주광역시");
INSERT INTO si VALUES(NULL, "울산광역시");
